services:
  - docker
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
before_install:
  - python --version
install:
  - pip install -r test-requirements.txt
  - python setup.py install
script:
  - pycodestyle --max-line-length=119 $(find ipython2cwl -name '*.py')
  - coverage run --source ipython2cwl -m unittest discover tests
after_script:
  - coveralls
matrix:
  include:
    - name: "Python 3.7 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.7 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install virtualenv
        - virtualenv -p python3 venv
        - source venv/bin/activate
        - pip3 install -U -r test-requirements.txt
      script: coverage run --source ipython2cwl -m unittest discover tests
      services:
        - docker